name: Deploy Obsidian Plugin

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'manifest.json'
      - 'styles.css'
      - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Get version
        id: version
        run: |
          echo "VERSION=$(grep '"version"' manifest.json | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: "AWS Quiz Plugin v${{ steps.version.outputs.VERSION }}"
          body: "Automatic release from main branch"
          files: |
            dist/main.js
            manifest.json
            styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}